import type { WebsiteInfo } from "./interfaces"

export const baseProviders: { [key: string]: WebsiteInfo } = {
  "amazon.com": {
    name: "Amazon",
    origin: "https://www.amazon.com",
    search: "/s?k=%s",
    affixes: ["amazon"],
  },
  "audible.com": {
    name: "Audible",
    origin: "https://www.audible.com",
    search: "/search?keywords=%s",
    affixes: ["audible"],
  },
  "baidu.com": {
    name: "Baidu",
    origin: "https://www.baidu.com",
    search: "/s?wd=%s",
    affixes: ["baidu"],
  },
  "bing.com": {
    name: "Bing",
    origin: "https://www.bing.com",
    search: "/search?q=%s",
    affixes: ["bing"],
  },
  "bing.com:ai": {
    name: "Bing AI",
    origin: "https://www.bing.com",
    search: "/copilotsearch?q=%s",
    affixes: ["bingai"],
  },
  "brave.com": {
    name: "Brave",
    origin: "https://search.brave.com",
    search: "/search?q=%s",
    affixes: ["brave"],
  },
  "calendar.proton.me": {
    name: "Proton Calendar",
    origin: "https://calendar.proton.me",
    search: "/search#keyword=%s",
    affixes: ["protoncalendar", "protcal"],
  },
  "chatgpt.com": {
    name: "Chat GPT",
    origin: "https://chatgpt.com",
    search: "?prompt=%s",
    affixes: ["chatgpt", "gpt"],
  },
  "chat.mistral.ai": {
    name: "Le Chat",
    origin: "https://chat.mistral.ai",
    search: "/chat?q=%s",
    affixes: ["mistral", "lechat"],
  },
  "claude.ai": {
    name: "Claude",
    origin: "https://claude.ai",
    affixes: ["claude"],
  },
  "copilot.microsoft.com": {
    name: "Copilot",
    origin: "https://copilot.microsoft.com/",
    affixes: ["copilot"],
  },
  "deepseek.com": {
    name: "DeepSeek",
    origin: "https://chat.deepseek.com",
    affixes: ["deepseek"],
  },
  "deezer.com": {
    name: "Deezer",
    origin: "https://www.deezer.com",
    search: "/search/%s",
    affixes: ["deezer"],
  },
  "drive.google.com": {
    name: "Google Drive",
    origin: "https://drive.google.com",
    search: "/drive/search?q=%s",
    affixes: ["googledrive", "gdrive"],
  },
  "drive.proton.me": {
    name: "Proton Drive",
    origin: "https://drive.proton.me",
    search: "/search#q=%s",
    affixes: ["protondrive", "protdrive"],
  },
  "dropbox.com": {
    name: "Dropbox",
    origin: "https://www.dropbox.com",
    search: "/search/personal?query=%s",
    affixes: ["dropbox"],
  },
  "duckduckgo.com": {
    name: "DuckDuckGo",
    origin: "https://duckduckgo.com",
    search: "/?q=%s",
    affixes: ["duckduckgo", "ddg"],
  },
  "duckduckgo.com:ai": {
    name: "Duck.ai",
    origin: "https://duckduckgo.com/?q=DuckDuckGo+AI+Chat&ia=chat&duckai=1",
    affixes: ["duckai", "ddgai"],
  },
  "ebay.com": {
    name: "eBay",
    origin: "https://www.ebay.com",
    search: "/sch/i.html?_nkw=%s",
    affixes: ["ebay"],
  },
  "ecosia.org": {
    name: "Ecosia",
    origin: "https://www.ecosia.org",
    search: "/search?q=%s",
    affixes: ["ecosia"],
  },
  "ecosia.org:ai": {
    name: "Ecosia AI",
    origin: "https://www.ecosia.org/ai-search",
    search: "https://www.ecosia.org/ai-search?q=%s",
    affixes: ["ecosiaai", "ecoai"],
  },
  "entertrained.app": {
    name: "Entertrained",
    origin: "https://entertrained.app",
    search: "/books?search=%s",
    affixes: ["entertrained"],
  },
  "epicgames.com": {
    name: "Epic Games",
    origin: "https://store.epicgames.com",
    search: "/browse?q=fortnite",
    affixes: ["epic", "epicgames", "epicstore"],
  },
  "etsy.com": {
    name: "Etsy",
    origin: "https://www.etsy.com",
    search: "/search?q=%s",
    affixes: ["etsy"],
  },
  "gemini.google.com": {
    name: "Gemini",
    origin: "https://gemini.google.com/",
    affixes: ["gemini"],
  },
  "gist.github.com": {
    name: "GitHub Gist",
    origin: "https://gist.github.com",
    search: "/search?q=%s",
    affixes: ["gist"],
  },
  "github.com": {
    name: "GitHub",
    origin: "https://github.com",
    search: "/search?q=%s",
    affixes: ["github", "gh"],
  },
  "grok.com": {
    name: "Grok",
    origin: "https://grok.com",
    search: "/?q=%s",
    affixes: ["grok"],
  },
  "mail.google.com": {
    name: "Gmail",
    origin: "https://mail.google.com",
    search: "/#search/%s",
    affixes: ["gmail"],
  },
  "gog.com": {
    name: "GOG",
    origin: "https://www.gog.com",
    search: "/games?query=%s",
    affixes: ["gog"],
  },
  "goodreads.com": {
    name: "",
    origin: "https://www.goodreads.com",
    search: "/search?q=%s",
    affixes: ["goodreads"],
  },
  "google.com": {
    name: "Google",
    origin: "https://www.google.com",
    search: "/search?q=%s",
    affixes: ["google"],
  },
  "google.com:ai": {
    name: "Google AI",
    origin: "https://www.google.com/search?q=&udm=50",
    search: "https://www.google.com/search?q=%s&udm=50",
    affixes: ["googleai", "gai"],
  },
  "google.com:web": {
    name: "Google Web",
    origin: "https://www.google.com/webhp?udm=14",
    search: "https://www.google.com/search?q=%s&udm=14",
    affixes: ["googleweb", "gweb"],
  },
  "instagram.com": {
    name: "Instagram",
    origin: "https://www.instagram.com",
    affixes: ["instagram", "insta"],
  },
  "itch.io": {
    name: "Itch.io",
    origin: "https://itch.io",
    search: "/search?q=%s",
    affixes: ["itch"],
  },
  "kagi.com": {
    name: "Kagi",
    origin: "https://kagi.com",
    search: "/search?q=%s",
    affixes: ["kagi"],
  },
  "lumo.proton.me": {
    name: "Lumo",
    origin: "https://lumo.proton.me",
    search: "/?q=%s",
    affixes: ["lumo"],
  },
  "mail.proton.me": {
    name: "Proton Mail",
    origin: "https://mail.proton.me",
    search: "/almost-all-mail#keyword=%s",
    affixes: ["proton", "protonmail", "protmail"],
  },
  "marginalia-search.com": {
    name: "Marginalia Search",
    origin: "https://marginalia-search.com",
    search: "/search?query=%s",
    affixes: ["marginalia"],
  },
  "mojeek.com": {
    name: "Mojeek",
    origin: "https://www.mojeek.com",
    search: "/search?q=%s",
    affixes: ["mojeek"],
  },
  "monkeytype.com": {
    name: "Monkeytype",
    origin: "https://monkeytype.com",
    affixes: ["mt", "monkeytype"],
  },
  "music.amazon.com": {
    name: "Amazon Music",
    origin: "https://music.amazon.com",
    search: "/search/%s",
    affixes: ["amazonmusic"],
  },
  "music.youtube.com": {
    name: "YouTube Music",
    origin: "https://music.youtube.com",
    search: "/search?q=%s",
    affixes: ["ytm", "youtubemusic"],
  },
  "npmjs.com": {
    name: "NPM",
    origin: "https://www.npmjs.com",
    search: "/search?q=%s",
    affixes: ["npm"],
  },
  "perplexity.ai": {
    name: "Perplexity",
    origin: "https://www.perplexity.ai",
    search: "/?q=%s",
    affixes: ["perplexity"],
  },
  "lexaloffle.com:pico8": {
    name: "Pico8",
    origin: "https://www.lexaloffle.com/pico-8.php",
    search:
      "https://www.lexaloffle.com/bbs/?cat=7&carts_tab=1&#sub=2&mode=carts&orderby=featured&search=%s",
    affixes: ["pico8"],
  },
  "pinterest.com": {
    name: "Pinterest",
    origin: "https://pl.pinterest.com",
    search: "/search/pins/?q=%s",
    affixes: ["pinterest"],
  },
  "quora.com": {
    name: "Quora",
    origin: "https://www.quora.com",
    search: "/search?q=%s",
    affixes: ["quora"],
  },
  "qwant.com": {
    name: "Qwant",
    origin: "https://www.qwant.com",
    search: "/?q=%s",
    affixes: ["qwant"],
  },
  "reddit.com": {
    name: "Reddit",
    origin: "https://www.reddit.com",
    search: "/search?q=%s",
    affixes: ["reddit", "r"],
  },
  "metasearx.com": {
    name: "searX",
    origin: "https://metasearx.com",
    search: "/?q=%s",
    affixes: ["metasearx", "searx"],
  },
  "soundcloud.com": {
    name: "SoundCloud",
    origin: "https://soundcloud.com",
    search: "/search?q=%s",
    affixes: ["soundcloud"],
  },
  "spotify.com": {
    name: "Spotify",
    origin: "https://open.spotify.com",
    searh: "/search/%s",
    affixes: ["spotify", "sp"],
  },
  "stackoverflow.com": {
    name: "Stack Overflow",
    origin: "https://stackoverflow.com",
    search: "/search?q=%s",
    affixes: ["stackoverflow", "so"],
  },
  "startpage.com": {
    name: "Startpage",
    origin: "https://www.startpage.com",
    search: "/sp/search?q=%s",
    affixes: ["startpage"],
  },
  "steampowered.com": {
    name: "Steam",
    origin: "https://store.steampowered.com",
    search: "/search?term=%s",
    affixes: ["steam", "steampowered"],
  },
  "tidal.com": {
    name: "Tidal",
    origin: "https://tidal.com",
    search: "/search?q=%s",
    affixes: ["tidal"],
  },
  "tiktok.com": {
    name: "TikTok",
    origin: "https://www.tiktok.com",
    search: "/search?q=%s",
    affixes: ["tiktok"],
  },
  "twitch.tv": {
    name: "Twitch",
    origin: "https://www.twitch.tv",
    search: "/search?term=%s",
    affixes: ["twitch"],
  },
  "x.com": {
    name: "X",
    origin: "https://x.com",
    search: "/search?q=%s",
    affixes: ["twitter", "x"],
  },
  "x.com:ai": {
    name: "X AI",
    origin: "https://x.com/i/grok",
    affixes: ["twitterai", "xai"],
  },
  "wikipedia.org": {
    name: "Wikipedia",
    origin: "https://en.wikipedia.org",
    search: "/w/index.php?search=%s",
    affixes: ["wikipedia", "wiki"],
  },
  "wolframalpha.com": {
    name: "Wolfram Alpha",
    origin: "https://www.wolframalpha.com",
    search: "/input?i=%s",
    affixes: ["wolframalpha", "wa"],
  },
  "yandex.com": {
    name: "Yandex",
    origin: "https://yandex.com",
    search: "/search/?text=%s",
    affixes: ["yandex"],
  },
  "youtube.com": {
    name: "YouTube",
    origin: "https://youtube.com",
    search: "/results?search_query=%s",
    affixes: ["youtube", "yt"],
  },
}
